# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='\u7b80\u4ecb')),
            ],
            options={
                'verbose_name': '\u7b80\u4ecb',
                'verbose_name_plural': '\u7b80\u4ecb',
            },
        ),
    ]
